-- Production intentionally has no fake auth users or rides.
-- Create test users through Supabase Auth in a local or staging project, then
-- insert staging-only ride fixtures that reference those real auth user IDs.
